services:

##Backend##
  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    container_name: n8n-server
    restart: unless-stopped
    environment:
      - DB_SQLITE_POOL_SIZE=20
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: